package net.hyper.chiseled.registry;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.hyper.chiseled.Chiseled;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ChiseledItemGroups {
    public static final ItemGroup CHISELED_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(Chiseled.MOD_ID, "chiseled"),
            FabricItemGroup.builder().icon(() -> new ItemStack(ChiseledBlocks.POLISHED_STONE))
                    .displayName(Text.translatable("creativetab.chiseled.chiseled_tab"))
                    .entries((displayContext, entries) -> {

                        entries.add(ChiseledBlocks.OAK_TRIM);
                        entries.add(ChiseledBlocks.SPRUCE_TRIM);
                        entries.add(ChiseledBlocks.BIRCH_TRIM);
                        entries.add(ChiseledBlocks.JUNGLE_TRIM);
                        entries.add(ChiseledBlocks.ACACIA_TRIM);
                        entries.add(ChiseledBlocks.DARK_OAK_TRIM);
                        entries.add(ChiseledBlocks.MANGROVE_TRIM);
                        entries.add(ChiseledBlocks.CHERRY_TRIM);
                        entries.add(ChiseledBlocks.BAMBOO_TRIM);
                        entries.add(ChiseledBlocks.CRIMSON_TRIM);
                        entries.add(ChiseledBlocks.WARPED_TRIM);

                        entries.add(ChiseledBlocks.STONE_WALL);
                        entries.add(ChiseledBlocks.POLISHED_STONE);
                        entries.add(ChiseledBlocks.POLISHED_STONE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_STONE_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_STONE_WALL);
                        entries.add(ChiseledBlocks.POLISHED_STONE_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.POLISHED_STONE_BUTTON);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_STONE);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_STONE_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_STONE_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_STONE_WALL);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_STONE_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_STONE_BUTTON);
                        entries.add(ChiseledBlocks.CRACKED_CHISELED_STONE_BRICKS);
                        entries.add(ChiseledBlocks.MOSSY_CHISELED_STONE_BRICKS);
                        entries.add(ChiseledBlocks.STONE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_STONE_TILES);
                        entries.add(ChiseledBlocks.STONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.STONE_TILE_SLAB);
                        entries.add(ChiseledBlocks.STONE_TILE_WALL);
                        entries.add(ChiseledBlocks.MOSSY_STONE_TILES);
                        entries.add(ChiseledBlocks.MOSSY_STONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_STONE_TILE_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_STONE_TILE_WALL);
                        entries.add(ChiseledBlocks.SMALL_STONE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SMALL_STONE_BRICKS);
                        entries.add(ChiseledBlocks.STONE_TRIM);
                        entries.add(ChiseledBlocks.CRACKED_STONE_TRIM);
                        entries.add(ChiseledBlocks.SMALL_STONE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_STONE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_STONE_BRICK_WALL);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_STONE_BRICKS);
                        entries.add(ChiseledBlocks.MOSSY_STONE_TRIM);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_WALL);
                        entries.add(ChiseledBlocks.MIXED_STONE_TILES);
                        entries.add(ChiseledBlocks.MIXED_STONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MIXED_STONE_TILE_SLAB);

                        entries.add(ChiseledBlocks.POLISHED_DEEPSLATE_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.POLISHED_DEEPSLATE_BUTTON);
                        entries.add(ChiseledBlocks.DEEPSLATE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_DEEPSLATE_TILES);
                        entries.add(ChiseledBlocks.DEEPSLATE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.DEEPSLATE_TILE_SLAB);
                        entries.add(ChiseledBlocks.DEEPSLATE_TILE_WALL);
                        entries.add(ChiseledBlocks.DEEPSLATE_TRIM);
                        entries.add(ChiseledBlocks.CRACKED_DEEPSLATE_TRIM);

                        entries.add(ChiseledBlocks.POLISHED_GRANITE_WALL);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_BUTTON);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_BRICK_WALL);
                        entries.add(ChiseledBlocks.CHISELED_POLISHED_GRANITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TILES);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_TILE_WALL);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SMALL_POLISHED_GRANITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_GRANITE_TRIM);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TRIM);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_WALL);

                        entries.add(ChiseledBlocks.POLISHED_DIORITE_WALL);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_BUTTON);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_BRICK_WALL);
                        entries.add(ChiseledBlocks.CHISELED_POLISHED_DIORITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TILES);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_TILE_WALL);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SMALL_POLISHED_DIORITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_DIORITE_TRIM);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TRIM);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_WALL);

                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_WALL);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_BUTTON);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_BRICK_WALL);
                        entries.add(ChiseledBlocks.CHISELED_POLISHED_ANDESITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TILES);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_TILE_WALL);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SMALL_POLISHED_ANDESITE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_ANDESITE_TRIM);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TRIM);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_WALL);

                        entries.add(ChiseledBlocks.MOSSY_CHISELED_TUFF);
                        entries.add(ChiseledBlocks.POLISHED_TUFF_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.POLISHED_TUFF_BUTTON);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_TUFF);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_TUFF_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_TUFF_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_TUFF_WALL);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_TUFF_PRESSURE_PLATE);
                        entries.add(ChiseledBlocks.MOSSY_POLISHED_TUFF_BUTTON);
                        entries.add(ChiseledBlocks.MOSSY_TUFF_BRICKS);
                        entries.add(ChiseledBlocks.MOSSY_TUFF_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_TUFF_BRICK_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_TUFF_BRICK_WALL);
                        entries.add(ChiseledBlocks.MOSSY_CHISELED_TUFF_BRICKS);

                        entries.add(ChiseledBlocks.WEATHERED_BRICKS);
                        entries.add(ChiseledBlocks.WEATHERED_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.WEATHERED_BRICK_SLAB);
                        entries.add(ChiseledBlocks.WEATHERED_BRICK_WALL);
                        entries.add(ChiseledBlocks.MOSSY_BRICKS);
                        entries.add(ChiseledBlocks.MOSSY_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_BRICK_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_BRICK_WALL);

                        entries.add(ChiseledBlocks.PACKED_MUD_STAIRS);
                        entries.add(ChiseledBlocks.PACKED_MUD_SLAB);
                        entries.add(ChiseledBlocks.PACKED_MUD_WALL);
                        entries.add(ChiseledBlocks.MOSSY_MUD_BRICKS);
                        entries.add(ChiseledBlocks.MOSSY_MUD_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_MUD_BRICK_WALL);
                        entries.add(ChiseledBlocks.MUD_TILES);
                        entries.add(ChiseledBlocks.MUD_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MUD_TILE_SLAB);
                        entries.add(ChiseledBlocks.MUD_TILE_WALL);
                        entries.add(ChiseledBlocks.MOSSY_MUD_TILES);
                        entries.add(ChiseledBlocks.MOSSY_MUD_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_MUD_TILE_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_MUD_TILE_WALL);
                        entries.add(ChiseledBlocks.SMALL_MUD_BRICKS);
                        entries.add(ChiseledBlocks.SMALL_MUD_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_MUD_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_MUD_BRICK_WALL);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_MUD_BRICKS);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_SLAB);
                        entries.add(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_WALL);

                        entries.add(ChiseledBlocks.SMOOTH_SANDSTONE_WALL);
                        entries.add(ChiseledBlocks.SANDSTONE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SANDSTONE_BRICKS);
                        entries.add(ChiseledBlocks.SANDSTONE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SANDSTONE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SANDSTONE_BRICK_WALL);
                        entries.add(ChiseledBlocks.SANDSTONE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_SANDSTONE_TILES);
                        entries.add(ChiseledBlocks.SANDSTONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.SANDSTONE_TILE_SLAB);

                        entries.add(ChiseledBlocks.MIXED_SANDSTONE_TILES);
                        entries.add(ChiseledBlocks.MIXED_SANDSTONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MIXED_SANDSTONE_TILE_SLAB);

                        entries.add(ChiseledBlocks.SMOOTH_RED_SANDSTONE_WALL);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_RED_SANDSTONE_BRICKS);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_BRICK_WALL);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_RED_SANDSTONE_TILES);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB);

                        entries.add(ChiseledBlocks.POLISHED_PRISMARINE);
                        entries.add(ChiseledBlocks.POLISHED_PRISMARINE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_PRISMARINE_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_PRISMARINE_WALL);
                        entries.add(ChiseledBlocks.PRISMARINE_BRICK_WALL);
                        entries.add(ChiseledBlocks.PRISMARINE_TILES);
                        entries.add(ChiseledBlocks.PRISMARINE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.PRISMARINE_TILE_SLAB);
                        entries.add(ChiseledBlocks.MIXED_PRISMARINE_TILES);
                        entries.add(ChiseledBlocks.MIXED_PRISMARINE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MIXED_PRISMARINE_TILE_SLAB);
                        entries.add(ChiseledBlocks.DARK_PRISMARINE_WALL);
                        entries.add(ChiseledBlocks.DARK_PRISMARINE_TILES);
                        entries.add(ChiseledBlocks.DARK_PRISMARINE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.DARK_PRISMARINE_TILE_SLAB);

                        entries.add(ChiseledBlocks.SMOOTH_BASALT_STAIRS);
                        entries.add(ChiseledBlocks.SMOOTH_BASALT_SLAB);
                        entries.add(ChiseledBlocks.SMOOTH_BASALT_WALL);

                        entries.add(ChiseledBlocks.GILDED_POLISHED_BLACKSTONE_BRICKS);
                        entries.add(ChiseledBlocks.POLISHED_BLACKSTONE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_POLISHED_BLACKSTONE_TILES);
                        entries.add(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_SLAB);
                        entries.add(ChiseledBlocks.GILDED_POLISHED_BLACKSTONE_TILES);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SMALL_POLISHED_BLACKSTONE_BRICKS);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_WALL);
                        entries.add(ChiseledBlocks.GILDED_SMALL_POLISHED_BLACKSTONE_BRICKS);
                        entries.add(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILES);
                        entries.add(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILE_SLAB);

                        entries.add(ChiseledBlocks.QUARTZ_WALL);
                        entries.add(ChiseledBlocks.SMOOTH_QUARTZ_WALL);
                        entries.add(ChiseledBlocks.QUARTZ_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.QUARTZ_BRICK_SLAB);
                        entries.add(ChiseledBlocks.QUARTZ_BRICK_WALL);
                        entries.add(ChiseledBlocks.QUARTZ_TILES);
                        entries.add(ChiseledBlocks.QUARTZ_TILE_STAIRS);
                        entries.add(ChiseledBlocks.QUARTZ_TILE_SLAB);

                        entries.add(ChiseledBlocks.END_STONE_STAIRS);
                        entries.add(ChiseledBlocks.END_STONE_SLAB);
                        entries.add(ChiseledBlocks.END_STONE_WALL);
                        entries.add(ChiseledBlocks.POLISHED_END_STONE);
                        entries.add(ChiseledBlocks.POLISHED_END_STONE_STAIRS);
                        entries.add(ChiseledBlocks.POLISHED_END_STONE_SLAB);
                        entries.add(ChiseledBlocks.POLISHED_END_STONE_WALL);
                        entries.add(ChiseledBlocks.CRACKED_END_STONE_BRICKS);
                        entries.add(ChiseledBlocks.CHISELED_END_STONE_BRICKS);
                        entries.add(ChiseledBlocks.END_STONE_TILES);
                        entries.add(ChiseledBlocks.CRACKED_END_STONE_TILES);
                        entries.add(ChiseledBlocks.END_STONE_TILE_STAIRS);
                        entries.add(ChiseledBlocks.END_STONE_TILE_SLAB);
                        entries.add(ChiseledBlocks.SMALL_END_STONE_BRICKS);
                        entries.add(ChiseledBlocks.CRACKED_SMALL_END_STONE_BRICKS);
                        entries.add(ChiseledBlocks.SMALL_END_STONE_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.SMALL_END_STONE_BRICK_SLAB);
                        entries.add(ChiseledBlocks.SMALL_END_STONE_BRICK_WALL);

                        entries.add(ChiseledBlocks.MIXED_PURPUR_TILES);
                        entries.add(ChiseledBlocks.MIXED_PURPUR_TILE_STAIRS);
                        entries.add(ChiseledBlocks.MIXED_PURPUR_TILE_SLAB);

                        entries.add(ChiseledBlocks.AMETHYST_STAIRS);
                        entries.add(ChiseledBlocks.AMETHYST_SLAB);
                        entries.add(ChiseledBlocks.AMETHYST_WALL);
                        entries.add(ChiseledBlocks.AMETHYST_BRICKS);
                        entries.add(ChiseledBlocks.AMETHYST_BRICK_STAIRS);
                        entries.add(ChiseledBlocks.AMETHYST_BRICK_SLAB);
                        entries.add(ChiseledBlocks.AMETHYST_BRICK_WALL);
                        entries.add(ChiseledBlocks.AMETHYST_TILES);
                        entries.add(ChiseledBlocks.AMETHYST_TILE_STAIRS);
                        entries.add(ChiseledBlocks.AMETHYST_TILE_SLAB);

                        entries.add(ChiseledBlocks.CALCITE_STAIRS);
                        entries.add(ChiseledBlocks.CALCITE_SLAB);
                        entries.add(ChiseledBlocks.CALCITE_WALL);

                        entries.add(ChiseledBlocks.TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.WHITE_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.WHITE_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.WHITE_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.GRAY_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.GRAY_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.GRAY_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.BLACK_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.BLACK_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.BLACK_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.BROWN_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.BROWN_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.BROWN_TERRACOTTA_WALL);

                        entries.add(ChiseledBlocks.RED_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.RED_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.RED_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.ORANGE_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.ORANGE_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.ORANGE_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.YELLOW_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.YELLOW_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.YELLOW_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.LIME_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.LIME_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.LIME_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.GREEN_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.GREEN_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.GREEN_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.CYAN_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.CYAN_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.CYAN_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.BLUE_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.BLUE_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.BLUE_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.PURPLE_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.PURPLE_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.PURPLE_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.MAGENTA_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.MAGENTA_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.MAGENTA_TERRACOTTA_WALL);
                        entries.add(ChiseledBlocks.PINK_TERRACOTTA_STAIRS);
                        entries.add(ChiseledBlocks.PINK_TERRACOTTA_SLAB);
                        entries.add(ChiseledBlocks.PINK_TERRACOTTA_WALL);

                        entries.add(ChiseledBlocks.WHITE_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.WHITE_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.WHITE_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.LIGHT_GRAY_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.LIGHT_GRAY_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.GRAY_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.GRAY_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.GRAY_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.BLACK_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.BLACK_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.BLACK_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.BROWN_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.BROWN_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.BROWN_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.RED_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.RED_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.RED_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.ORANGE_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.ORANGE_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.ORANGE_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.YELLOW_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.YELLOW_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.YELLOW_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.LIME_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.LIME_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.LIME_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.GREEN_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.GREEN_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.GREEN_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.CYAN_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.CYAN_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.CYAN_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.LIGHT_BLUE_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.LIGHT_BLUE_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.BLUE_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.BLUE_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.BLUE_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.PURPLE_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.PURPLE_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.PURPLE_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.MAGENTA_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.MAGENTA_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.MAGENTA_CONCRETE_WALL);
                        entries.add(ChiseledBlocks.PINK_CONCRETE_STAIRS);
                        entries.add(ChiseledBlocks.PINK_CONCRETE_SLAB);
                        entries.add(ChiseledBlocks.PINK_CONCRETE_WALL);

                        entries.add(ChiseledBlocks.FRAMED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_WHITE_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_LIGHT_GRAY_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_GRAY_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_BLACK_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_BROWN_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_RED_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_ORANGE_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_YELLOW_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_LIME_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_GREEN_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_CYAN_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_LIGHT_BLUE_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_BLUE_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_PURPLE_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_MAGENTA_STAINED_GLASS);
                        entries.add(ChiseledBlocks.FRAMED_PINK_STAINED_GLASS);

                        entries.add(ChiseledBlocks.FRAMED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_WHITE_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_LIGHT_GRAY_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_GRAY_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_BLACK_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_BROWN_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_RED_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_ORANGE_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_YELLOW_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_LIME_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_GREEN_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_CYAN_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_LIGHT_BLUE_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_BLUE_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_PURPLE_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_MAGENTA_STAINED_GLASS_PANE);
                        entries.add(ChiseledBlocks.FRAMED_PINK_STAINED_GLASS_PANE);

                    }).build());

    public static void registerChiseledItemGroups() {
    }
}