package net.hyper.chiseled.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.hyper.chiseled.registry.ChiseledBlocks;
import net.minecraft.registry.RegistryWrapper;

import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(ChiseledBlocks.VERTICAL_OAK_PLANKS);
        addDrop(ChiseledBlocks.VERTICAL_OAK_STAIRS);
        addDrop(ChiseledBlocks.VERTICAL_OAK_SLAB, slabDrops(ChiseledBlocks.VERTICAL_OAK_SLAB));

        addDrop(ChiseledBlocks.STONE_WALL);
        addDrop(ChiseledBlocks.POLISHED_STONE);
        addDrop(ChiseledBlocks.POLISHED_STONE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_STONE_SLAB, slabDrops(ChiseledBlocks.POLISHED_STONE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_STONE_WALL);
        addDrop(ChiseledBlocks.POLISHED_STONE_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.POLISHED_STONE_BUTTON);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_STONE);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_STONE_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_STONE_SLAB, slabDrops(ChiseledBlocks.MOSSY_POLISHED_STONE_SLAB));
        addDrop(ChiseledBlocks.MOSSY_POLISHED_STONE_WALL);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_STONE_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_STONE_BUTTON);
        addDrop(ChiseledBlocks.CRACKED_CHISELED_STONE_BRICKS);
        addDrop(ChiseledBlocks.MOSSY_CHISELED_STONE_BRICKS);
        addDrop(ChiseledBlocks.STONE_TILES);
        addDrop(ChiseledBlocks.CRACKED_STONE_TILES);
        addDrop(ChiseledBlocks.STONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.STONE_TILE_SLAB, slabDrops(ChiseledBlocks.STONE_TILE_SLAB));
        addDrop(ChiseledBlocks.STONE_TILE_WALL);
        addDrop(ChiseledBlocks.MOSSY_STONE_TILES);
        addDrop(ChiseledBlocks.MOSSY_STONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_STONE_TILE_SLAB, slabDrops(ChiseledBlocks.MOSSY_STONE_TILE_SLAB));
        addDrop(ChiseledBlocks.MOSSY_STONE_TILE_WALL);
        addDrop(ChiseledBlocks.SMALL_STONE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SMALL_STONE_BRICKS);
        addDrop(ChiseledBlocks.SMALL_STONE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_STONE_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_STONE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_STONE_BRICK_WALL);
        addDrop(ChiseledBlocks.MOSSY_SMALL_STONE_BRICKS);
        addDrop(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_SLAB, slabDrops(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_SLAB));
        addDrop(ChiseledBlocks.MOSSY_SMALL_STONE_BRICK_WALL);
        addDrop(ChiseledBlocks.MIXED_STONE_TILES);
        addDrop(ChiseledBlocks.MIXED_STONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.MIXED_STONE_TILE_SLAB, slabDrops(ChiseledBlocks.MIXED_STONE_TILE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_GRANITE_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_BUTTON);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_WALL);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_GRANITE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB, slabDrops(ChiseledBlocks.POLISHED_GRANITE_BRICK_SLAB));
        addDrop(ChiseledBlocks.POLISHED_GRANITE_BRICK_WALL);
        addDrop(ChiseledBlocks.CHISELED_POLISHED_GRANITE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_TILES);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TILES);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_TILE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB, slabDrops(ChiseledBlocks.POLISHED_GRANITE_TILE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_GRANITE_TILE_WALL);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_WALL);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_BUTTON);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_DIORITE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB, slabDrops(ChiseledBlocks.POLISHED_DIORITE_BRICK_SLAB));
        addDrop(ChiseledBlocks.POLISHED_DIORITE_BRICK_WALL);
        addDrop(ChiseledBlocks.CHISELED_POLISHED_DIORITE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_TILES);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TILES);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_TILE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB, slabDrops(ChiseledBlocks.POLISHED_DIORITE_TILE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_DIORITE_TILE_WALL);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_WALL);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_BUTTON);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB, slabDrops(ChiseledBlocks.POLISHED_ANDESITE_BRICK_SLAB));
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_BRICK_WALL);
        addDrop(ChiseledBlocks.CHISELED_POLISHED_ANDESITE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_TILES);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TILES);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_TILE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB, slabDrops(ChiseledBlocks.POLISHED_ANDESITE_TILE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_TILE_WALL);
        addDrop(ChiseledBlocks.POLISHED_DEEPSLATE_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.POLISHED_DEEPSLATE_BUTTON);
        addDrop(ChiseledBlocks.DEEPSLATE_TILES);
        addDrop(ChiseledBlocks.CRACKED_DEEPSLATE_TILES);
        addDrop(ChiseledBlocks.DEEPSLATE_TILE_STAIRS);
        addDrop(ChiseledBlocks.DEEPSLATE_TILE_SLAB, slabDrops(ChiseledBlocks.DEEPSLATE_TILE_SLAB));
        addDrop(ChiseledBlocks.DEEPSLATE_TILE_WALL);
        addDrop(ChiseledBlocks.MOSSY_BRICKS);
        addDrop(ChiseledBlocks.MOSSY_BRICK_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_BRICK_SLAB, slabDrops(ChiseledBlocks.MOSSY_BRICK_SLAB));
        addDrop(ChiseledBlocks.MOSSY_BRICK_WALL);
        addDrop(ChiseledBlocks.WEATHERED_BRICKS);
        addDrop(ChiseledBlocks.WEATHERED_BRICK_STAIRS);
        addDrop(ChiseledBlocks.WEATHERED_BRICK_SLAB, slabDrops(ChiseledBlocks.WEATHERED_BRICK_SLAB));
        addDrop(ChiseledBlocks.WEATHERED_BRICK_WALL);
        addDrop(ChiseledBlocks.PACKED_MUD_STAIRS);
        addDrop(ChiseledBlocks.PACKED_MUD_SLAB, slabDrops(ChiseledBlocks.PACKED_MUD_SLAB));
        addDrop(ChiseledBlocks.PACKED_MUD_WALL);
        addDrop(ChiseledBlocks.MOSSY_MUD_BRICKS);
        addDrop(ChiseledBlocks.MOSSY_MUD_BRICK_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB, slabDrops(ChiseledBlocks.MOSSY_MUD_BRICK_SLAB));
        addDrop(ChiseledBlocks.MOSSY_MUD_BRICK_WALL);
        addDrop(ChiseledBlocks.MUD_TILES);
        addDrop(ChiseledBlocks.MUD_TILE_STAIRS);
        addDrop(ChiseledBlocks.MUD_TILE_SLAB, slabDrops(ChiseledBlocks.MUD_TILE_SLAB));
        addDrop(ChiseledBlocks.MUD_TILE_WALL);
        addDrop(ChiseledBlocks.MOSSY_MUD_TILES);
        addDrop(ChiseledBlocks.MOSSY_MUD_TILE_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_MUD_TILE_SLAB, slabDrops(ChiseledBlocks.MOSSY_MUD_TILE_SLAB));
        addDrop(ChiseledBlocks.MOSSY_MUD_TILE_WALL);
        addDrop(ChiseledBlocks.SMALL_MUD_BRICKS);
        addDrop(ChiseledBlocks.SMALL_MUD_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_MUD_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_MUD_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_MUD_BRICK_WALL);
        addDrop(ChiseledBlocks.MOSSY_SMALL_MUD_BRICKS);
        addDrop(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_SLAB, slabDrops(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_SLAB));
        addDrop(ChiseledBlocks.MOSSY_SMALL_MUD_BRICK_WALL);
        addDrop(ChiseledBlocks.SMOOTH_SANDSTONE_WALL);
        addDrop(ChiseledBlocks.SANDSTONE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SANDSTONE_BRICKS);
        addDrop(ChiseledBlocks.SANDSTONE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SANDSTONE_BRICK_SLAB, slabDrops(ChiseledBlocks.SANDSTONE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SANDSTONE_BRICK_WALL);
        addDrop(ChiseledBlocks.SANDSTONE_TILES);
        addDrop(ChiseledBlocks.CRACKED_SANDSTONE_TILES);
        addDrop(ChiseledBlocks.SANDSTONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.SANDSTONE_TILE_SLAB, slabDrops(ChiseledBlocks.SANDSTONE_TILE_SLAB));
        addDrop(ChiseledBlocks.MIXED_SANDSTONE_TILES);
        addDrop(ChiseledBlocks.MIXED_SANDSTONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.MIXED_SANDSTONE_TILE_SLAB, slabDrops(ChiseledBlocks.MIXED_SANDSTONE_TILE_SLAB));
        addDrop(ChiseledBlocks.SMOOTH_RED_SANDSTONE_WALL);
        addDrop(ChiseledBlocks.RED_SANDSTONE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_RED_SANDSTONE_BRICKS);
        addDrop(ChiseledBlocks.RED_SANDSTONE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB, slabDrops(ChiseledBlocks.RED_SANDSTONE_BRICK_SLAB));
        addDrop(ChiseledBlocks.RED_SANDSTONE_BRICK_WALL);
        addDrop(ChiseledBlocks.RED_SANDSTONE_TILES);
        addDrop(ChiseledBlocks.CRACKED_RED_SANDSTONE_TILES);
        addDrop(ChiseledBlocks.RED_SANDSTONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB, slabDrops(ChiseledBlocks.RED_SANDSTONE_TILE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_PRISMARINE);
        addDrop(ChiseledBlocks.POLISHED_PRISMARINE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_PRISMARINE_SLAB, slabDrops(ChiseledBlocks.POLISHED_PRISMARINE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_PRISMARINE_WALL);
        addDrop(ChiseledBlocks.PRISMARINE_BRICK_WALL);
        addDrop(ChiseledBlocks.PRISMARINE_TILES);
        addDrop(ChiseledBlocks.PRISMARINE_TILE_STAIRS);
        addDrop(ChiseledBlocks.PRISMARINE_TILE_SLAB, slabDrops(ChiseledBlocks.PRISMARINE_TILE_SLAB));
        addDrop(ChiseledBlocks.MIXED_PRISMARINE_TILES);
        addDrop(ChiseledBlocks.MIXED_PRISMARINE_TILE_STAIRS);
        addDrop(ChiseledBlocks.MIXED_PRISMARINE_TILE_SLAB, slabDrops(ChiseledBlocks.MIXED_PRISMARINE_TILE_SLAB));
        addDrop(ChiseledBlocks.DARK_PRISMARINE_WALL);
        addDrop(ChiseledBlocks.DARK_PRISMARINE_TILES);
        addDrop(ChiseledBlocks.DARK_PRISMARINE_TILE_STAIRS);
        addDrop(ChiseledBlocks.DARK_PRISMARINE_TILE_SLAB, slabDrops(ChiseledBlocks.DARK_PRISMARINE_TILE_SLAB));
        addDrop(ChiseledBlocks.SMOOTH_BASALT_STAIRS);
        addDrop(ChiseledBlocks.SMOOTH_BASALT_SLAB, slabDrops(ChiseledBlocks.SMOOTH_BASALT_SLAB));
        addDrop(ChiseledBlocks.SMOOTH_BASALT_WALL);
        addDrop(ChiseledBlocks.GILDED_POLISHED_BLACKSTONE_BRICKS);
        addDrop(ChiseledBlocks.POLISHED_BLACKSTONE_TILES);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_BLACKSTONE_TILES);
        addDrop(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_SLAB, slabDrops(ChiseledBlocks.POLISHED_BLACKSTONE_TILE_SLAB));
        addDrop(ChiseledBlocks.GILDED_POLISHED_BLACKSTONE_TILES);
        addDrop(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SMALL_POLISHED_BLACKSTONE_BRICKS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_POLISHED_BLACKSTONE_BRICK_WALL);
        addDrop(ChiseledBlocks.GILDED_SMALL_POLISHED_BLACKSTONE_BRICKS);
        addDrop(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILES);
        addDrop(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILE_SLAB, slabDrops(ChiseledBlocks.MIXED_POLISHED_BLACKSTONE_TILE_SLAB));
        addDrop(ChiseledBlocks.END_STONE_STAIRS);
        addDrop(ChiseledBlocks.END_STONE_SLAB, slabDrops(ChiseledBlocks.END_STONE_SLAB));
        addDrop(ChiseledBlocks.END_STONE_WALL);
        addDrop(ChiseledBlocks.POLISHED_END_STONE);
        addDrop(ChiseledBlocks.POLISHED_END_STONE_STAIRS);
        addDrop(ChiseledBlocks.POLISHED_END_STONE_SLAB, slabDrops(ChiseledBlocks.POLISHED_END_STONE_SLAB));
        addDrop(ChiseledBlocks.POLISHED_END_STONE_WALL);
        addDrop(ChiseledBlocks.CRACKED_END_STONE_BRICKS);
        addDrop(ChiseledBlocks.CHISELED_END_STONE_BRICKS);
        addDrop(ChiseledBlocks.END_STONE_TILES);
        addDrop(ChiseledBlocks.CRACKED_END_STONE_TILES);
        addDrop(ChiseledBlocks.END_STONE_TILE_STAIRS);
        addDrop(ChiseledBlocks.END_STONE_TILE_SLAB, slabDrops(ChiseledBlocks.END_STONE_TILE_SLAB));
        addDrop(ChiseledBlocks.SMALL_END_STONE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SMALL_END_STONE_BRICKS);
        addDrop(ChiseledBlocks.SMALL_END_STONE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_END_STONE_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_END_STONE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_END_STONE_BRICK_WALL);
        addDrop(ChiseledBlocks.MIXED_PURPUR_TILES);
        addDrop(ChiseledBlocks.MIXED_PURPUR_TILE_STAIRS);
        addDrop(ChiseledBlocks.MIXED_PURPUR_TILE_SLAB, slabDrops(ChiseledBlocks.MIXED_PURPUR_TILE_SLAB));
        addDrop(ChiseledBlocks.NETHERITE_STAIRS);
        addDrop(ChiseledBlocks.QUARTZ_WALL);
        addDrop(ChiseledBlocks.SMOOTH_QUARTZ_WALL);
        addDrop(ChiseledBlocks.QUARTZ_BRICK_STAIRS);
        addDrop(ChiseledBlocks.QUARTZ_BRICK_SLAB, slabDrops(ChiseledBlocks.QUARTZ_BRICK_SLAB));
        addDrop(ChiseledBlocks.QUARTZ_BRICK_WALL);
        addDrop(ChiseledBlocks.QUARTZ_TILES);
        addDrop(ChiseledBlocks.QUARTZ_TILE_STAIRS);
        addDrop(ChiseledBlocks.QUARTZ_TILE_SLAB, slabDrops(ChiseledBlocks.QUARTZ_TILE_SLAB));
        addDrop(ChiseledBlocks.AMETHYST_STAIRS);
        addDrop(ChiseledBlocks.AMETHYST_SLAB, slabDrops(ChiseledBlocks.AMETHYST_SLAB));
        addDrop(ChiseledBlocks.AMETHYST_WALL);
        addDrop(ChiseledBlocks.AMETHYST_BRICKS);
        addDrop(ChiseledBlocks.AMETHYST_BRICK_STAIRS);
        addDrop(ChiseledBlocks.AMETHYST_BRICK_SLAB, slabDrops(ChiseledBlocks.AMETHYST_BRICK_SLAB));
        addDrop(ChiseledBlocks.AMETHYST_BRICK_WALL);
        addDrop(ChiseledBlocks.AMETHYST_TILES);
        addDrop(ChiseledBlocks.AMETHYST_TILE_STAIRS);
        addDrop(ChiseledBlocks.AMETHYST_TILE_SLAB, slabDrops(ChiseledBlocks.AMETHYST_TILE_SLAB));
        addDrop(ChiseledBlocks.TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.WHITE_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.WHITE_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.WHITE_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.WHITE_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.GRAY_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.GRAY_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.GRAY_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.GRAY_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.BLACK_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.BLACK_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.BLACK_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.BLACK_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.BROWN_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.BROWN_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.BROWN_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.BROWN_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.RED_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.RED_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.RED_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.RED_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.ORANGE_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.ORANGE_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.ORANGE_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.ORANGE_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.YELLOW_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.YELLOW_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.YELLOW_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.YELLOW_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.LIME_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.LIME_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.LIME_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.LIME_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.GREEN_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.GREEN_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.GREEN_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.GREEN_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.CYAN_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.CYAN_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.CYAN_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.CYAN_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.BLUE_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.BLUE_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.BLUE_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.BLUE_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.PURPLE_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.PURPLE_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.PURPLE_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.PURPLE_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.MAGENTA_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.MAGENTA_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.MAGENTA_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.MAGENTA_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.PINK_TERRACOTTA_STAIRS);
        addDrop(ChiseledBlocks.PINK_TERRACOTTA_SLAB, slabDrops(ChiseledBlocks.PINK_TERRACOTTA_SLAB));
        addDrop(ChiseledBlocks.PINK_TERRACOTTA_WALL);
        addDrop(ChiseledBlocks.WHITE_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.WHITE_CONCRETE_SLAB, slabDrops(ChiseledBlocks.WHITE_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.WHITE_CONCRETE_WALL);
        addDrop(ChiseledBlocks.LIGHT_GRAY_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.LIGHT_GRAY_CONCRETE_SLAB, slabDrops(ChiseledBlocks.LIGHT_GRAY_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.LIGHT_GRAY_CONCRETE_WALL);
        addDrop(ChiseledBlocks.GRAY_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.GRAY_CONCRETE_SLAB, slabDrops(ChiseledBlocks.GRAY_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.GRAY_CONCRETE_WALL);
        addDrop(ChiseledBlocks.BLACK_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.BLACK_CONCRETE_SLAB, slabDrops(ChiseledBlocks.BLACK_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.BLACK_CONCRETE_WALL);
        addDrop(ChiseledBlocks.BROWN_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.BROWN_CONCRETE_SLAB, slabDrops(ChiseledBlocks.BROWN_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.BROWN_CONCRETE_WALL);
        addDrop(ChiseledBlocks.RED_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.RED_CONCRETE_SLAB, slabDrops(ChiseledBlocks.RED_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.RED_CONCRETE_WALL);
        addDrop(ChiseledBlocks.ORANGE_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.ORANGE_CONCRETE_SLAB, slabDrops(ChiseledBlocks.ORANGE_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.ORANGE_CONCRETE_WALL);
        addDrop(ChiseledBlocks.YELLOW_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.YELLOW_CONCRETE_SLAB, slabDrops(ChiseledBlocks.YELLOW_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.YELLOW_CONCRETE_WALL);
        addDrop(ChiseledBlocks.LIME_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.LIME_CONCRETE_SLAB, slabDrops(ChiseledBlocks.LIME_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.LIME_CONCRETE_WALL);
        addDrop(ChiseledBlocks.GREEN_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.GREEN_CONCRETE_SLAB, slabDrops(ChiseledBlocks.GREEN_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.GREEN_CONCRETE_WALL);
        addDrop(ChiseledBlocks.CYAN_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.CYAN_CONCRETE_SLAB, slabDrops(ChiseledBlocks.CYAN_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.CYAN_CONCRETE_WALL);
        addDrop(ChiseledBlocks.LIGHT_BLUE_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.LIGHT_BLUE_CONCRETE_SLAB, slabDrops(ChiseledBlocks.LIGHT_BLUE_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.LIGHT_BLUE_CONCRETE_WALL);
        addDrop(ChiseledBlocks.BLUE_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.BLUE_CONCRETE_SLAB, slabDrops(ChiseledBlocks.BLUE_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.BLUE_CONCRETE_WALL);
        addDrop(ChiseledBlocks.PURPLE_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.PURPLE_CONCRETE_SLAB, slabDrops(ChiseledBlocks.PURPLE_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.PURPLE_CONCRETE_WALL);
        addDrop(ChiseledBlocks.MAGENTA_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.MAGENTA_CONCRETE_SLAB, slabDrops(ChiseledBlocks.MAGENTA_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.MAGENTA_CONCRETE_WALL);
        addDrop(ChiseledBlocks.PINK_CONCRETE_STAIRS);
        addDrop(ChiseledBlocks.PINK_CONCRETE_SLAB, slabDrops(ChiseledBlocks.PINK_CONCRETE_SLAB));
        addDrop(ChiseledBlocks.PINK_CONCRETE_WALL);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_WHITE_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_LIGHT_GRAY_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_GRAY_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_BLACK_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_BROWN_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_RED_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_ORANGE_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_YELLOW_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_LIME_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_GREEN_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_CYAN_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_LIGHT_BLUE_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_BLUE_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_PURPLE_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_MAGENTA_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_PINK_STAINED_GLASS);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_WHITE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_LIGHT_GRAY_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_GRAY_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_BLACK_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_BROWN_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_RED_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_ORANGE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_YELLOW_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_LIME_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_GREEN_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_CYAN_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_LIGHT_BLUE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_BLUE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_PURPLE_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_MAGENTA_STAINED_GLASS_PANE);
        addDropWithSilkTouch(ChiseledBlocks.FRAMED_PINK_STAINED_GLASS_PANE);
        addDrop(ChiseledBlocks.CALCITE_STAIRS);
        addDrop(ChiseledBlocks.CALCITE_SLAB, slabDrops(ChiseledBlocks.CALCITE_SLAB));
        addDrop(ChiseledBlocks.CALCITE_WALL);
        addDrop(ChiseledBlocks.MOSSY_CHISELED_TUFF);
        addDrop(ChiseledBlocks.POLISHED_TUFF_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.POLISHED_TUFF_BUTTON);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_TUFF);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_TUFF_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_TUFF_SLAB);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_TUFF_WALL);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_TUFF_PRESSURE_PLATE);
        addDrop(ChiseledBlocks.MOSSY_POLISHED_TUFF_BUTTON);
        addDrop(ChiseledBlocks.MOSSY_TUFF_BRICKS);
        addDrop(ChiseledBlocks.MOSSY_TUFF_BRICK_STAIRS);
        addDrop(ChiseledBlocks.MOSSY_TUFF_BRICK_SLAB);
        addDrop(ChiseledBlocks.MOSSY_TUFF_BRICK_WALL);
        addDrop(ChiseledBlocks.MOSSY_CHISELED_TUFF_BRICKS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SMALL_POLISHED_GRANITE_BRICKS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_POLISHED_GRANITE_BRICK_WALL);
        addDrop(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SMALL_POLISHED_DIORITE_BRICKS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_POLISHED_DIORITE_BRICK_WALL);
        addDrop(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICKS);
        addDrop(ChiseledBlocks.CRACKED_SMALL_POLISHED_ANDESITE_BRICKS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_STAIRS);
        addDrop(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_SLAB, slabDrops(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_SLAB));
        addDrop(ChiseledBlocks.SMALL_POLISHED_ANDESITE_BRICK_WALL);
        addDrop(ChiseledBlocks.OAK_TRIM);
        addDrop(ChiseledBlocks.SPRUCE_TRIM);
        addDrop(ChiseledBlocks.BIRCH_TRIM);
        addDrop(ChiseledBlocks.JUNGLE_TRIM);
        addDrop(ChiseledBlocks.ACACIA_TRIM);
        addDrop(ChiseledBlocks.DARK_OAK_TRIM);
        addDrop(ChiseledBlocks.MANGROVE_TRIM);
        addDrop(ChiseledBlocks.CHERRY_TRIM);
        addDrop(ChiseledBlocks.BAMBOO_TRIM);
        addDrop(ChiseledBlocks.CRIMSON_TRIM);
        addDrop(ChiseledBlocks.WARPED_TRIM);
        addDrop(ChiseledBlocks.STONE_TRIM);
        addDrop(ChiseledBlocks.CRACKED_STONE_TRIM);
        addDrop(ChiseledBlocks.MOSSY_STONE_TRIM);
        addDrop(ChiseledBlocks.DEEPSLATE_TRIM);
        addDrop(ChiseledBlocks.CRACKED_DEEPSLATE_TRIM);
        addDrop(ChiseledBlocks.POLISHED_GRANITE_TRIM);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_GRANITE_TRIM);
        addDrop(ChiseledBlocks.POLISHED_DIORITE_TRIM);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_DIORITE_TRIM);
        addDrop(ChiseledBlocks.POLISHED_ANDESITE_TRIM);
        addDrop(ChiseledBlocks.CRACKED_POLISHED_ANDESITE_TRIM);
    }
}